In [4]:
import pandas as pd
data={
    'name':['maddy','axsh','dhanush','sandeep'],
    'age':[20,19,20,22],
    'city':['ariyalur','bangalore','tirutani','ambur'],
    'gender':['male','female','male','male'],
    'qualification':['b.tech','b.tech','b.tech','b.tech'],
    'salry':[25000,30000,250000,10000]
}

df = pd.DataFrame(data)

In [9]:
df

      name  age       city  gender qualification   salry
0    maddy   20   ariyalur    male        b.tech   25000
1     axsh   19  bangalore  female        b.tech   30000
2  dhanush   20   tirutani    male        b.tech  250000
3  sandeep   22      ambur    male        b.tech   10000

In [7]:
df.shape

(4, 6)

In [8]:
df.size

24

In [12]:
df.tail(3)

      name  age       city  gender qualification   salry
1     axsh   19  bangalore  female        b.tech   30000
2  dhanush   20   tirutani    male        b.tech  250000
3  sandeep   22      ambur    male        b.tech   10000

In [13]:
df.head(2)

    name  age       city  gender qualification  salry
0  maddy   20   ariyalur    male        b.tech  25000
1   axsh   19  bangalore  female        b.tech  30000

In [15]:
df.columns

Index(['name', 'age', 'city', 'gender', 'qualification', 'salry'], dtype='object')

In [19]:
df.columns.values

array(['name', 'age', 'city', 'gender', 'qualification', 'salry'],
      dtype=object)

In [24]:
df.columns[1]

'age'

In [28]:
data= pd.read_csv("/content/archive.zip")

In [36]:
data

,roll_no,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,science_score,total_score,grade
0,std-01,male,group D,some college,1.0,1.0,89,38.0,85.0,26.0,238.0,C
1,std-02,male,group B,high school,1.0,0.0,65,100.0,67.0,96.0,328.0,A
2,std-03,male,group C,master's degree,1.0,0.0,10,99.0,97.0,58.0,264.0,B
3,std-04,male,group D,some college,1.0,1.0,22,51.0,41.0,84.0,198.0,D
4,std-05,male,group C,some college,0.0,1.0,26,58.0,64.0,65.0,213.0,C
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,std-9996,female,group C,some college,1.0,0.0,78,60.0,46.0,58.0,242.0,C
9996,std-9997,female,group C,bachelor's degree,1.0,0.0,37,92.0,99.0,73.0,301.0,B
9997,std-9998,female,group B,associate's degree,1.0,1.0,70,71.0,100.0,90.0,331.0,A
9998,std-9999,female,group B,some high school,1.0,0.0,87,60.0,100.0,89.0,336.0,A
9999,std-10000,female,group B,high school,1.0,0.0,31,89.0,93.0,80.0,293.0,B

In [38]:
data.head(20)

,roll_no,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,science_score,total_score,grade
0,std-01,male,group D,some college,1.0,1.0,89,38.0,85.0,26.0,238.0,C
1,std-02,male,group B,high school,1.0,0.0,65,100.0,67.0,96.0,328.0,A
2,std-03,male,group C,master's degree,1.0,0.0,10,99.0,97.0,58.0,264.0,B
3,std-04,male,group D,some college,1.0,1.0,22,51.0,41.0,84.0,198.0,D
4,std-05,male,group C,some college,0.0,1.0,26,58.0,64.0,65.0,213.0,C
5,std-06,male,group B,high school,1.0,0.0,40,49.0,69.0,48.0,206.0,C
6,std-07,NaN,group C,some college,0.0,0.0,34,48.0,84.0,73.0,239.0,C
7,std-08,male,group B,associate's degree,1.0,1.0,25,80.0,34.0,17.0,156.0,D
8,std-09,male,group C,NaN,1.0,1.0,28,79.0,100.0,76.0,283.0,B
9,std-10,male,group C,some high school,NaN,0.0,71,22.0,85.0,39.0,217.0,C
10,std-11,male,group C,high school,1.0,NaN,55,64.0,87.0,60.0,266.0,B
11,std-12,male,group E,associate's degree,1.0,0.0,NaN,53.0,54.0,55.0,228.0,C
12,std-13,male,group A,associate's degree,1.0,0.0,29,NaN,76.0,91.0,293.0,B
13,std-14,male,group E,high school,0.0,1.0,18,70.0,NaN,45.0,162.0,D
14,std-15,male,A,associate's degree,1.0,1.0,72,97.0,52.0,NaN,289.0,B
15,std-16,male,group D,master's degree,0.0,0.0,23,96.0,34.0,54.0,NaN,C
16,std-17,male,group E,some high school,0.0,0.0,35,70.0,87.0,91.0,283.0,NaN
17,std-18,male,group B,some college,0.0,1.0,38,82.0,82.0,73.0,NaN,B
18,std-19,Boy,group C,bachelor's degree,1.0,1.0,41,76.0,78.0,NaN,280.0,B
19,std-20,male,group B,some high school,1.0,1.0,22,73.0,NaN,75.0,224.0,C

In [39]:
data.tail(999)

,roll_no,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,science_score,total_score,grade
9001,std-9002,female,group C,some high school,1.0,0.0,76,82.0,75.0,54.0,287.0,B
9002,std-9003,female,group D,some college,1.0,1.0,65,63.0,77.0,61.0,266.0,B
9003,std-9004,female,group C,high school,1.0,1.0,57,65.0,93.0,85.0,300.0,B
9004,std-9005,female,group C,bachelor's degree,1.0,1.0,76,32.0,95.0,93.0,296.0,B
9005,std-9006,female,group B,some college,0.0,0.0,74,66.0,76.0,81.0,297.0,B
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,std-9996,female,group C,some college,1.0,0.0,78,60.0,46.0,58.0,242.0,C
9996,std-9997,female,group C,bachelor's degree,1.0,0.0,37,92.0,99.0,73.0,301.0,B
9997,std-9998,female,group B,associate's degree,1.0,1.0,70,71.0,100.0,90.0,331.0,A
9998,std-9999,female,group B,some high school,1.0,0.0,87,60.0,100.0,89.0,336.0,A
9999,std-10000,female,group B,high school,1.0,0.0,31,89.0,93.0,80.0,293.0,B

In [40]:
data.columns.values

array(['roll_no', 'gender', 'race_ethnicity',
       'parental_level_of_education', 'lunch', 'test_preparation_course',
       'math_score', 'reading_score', 'writing_score', 'science_score',
       'total_score', 'grade'], dtype=object)

In [41]:
data.columns

Index(['roll_no', 'gender', 'race_ethnicity', 'parental_level_of_education',
       'lunch', 'test_preparation_course', 'math_score', 'reading_score',
       'writing_score', 'science_score', 'total_score', 'grade'],
      dtype='object')

In [45]:
data.columns[11]

'grade'

In [46]:
data.shape

(10000, 12)

In [47]:
data.size

120000

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   roll_no                      9999 non-null   object
 1   gender                       9982 non-null   object
 2   race_ethnicity               9977 non-null   object
 3   parental_level_of_education  9978 non-null   object
 4   lunch                        9976 non-null   float64
 5   test_preparation_course      9977 non-null   float64
 6   math_score                   9976 non-null   object
 7   reading_score                9975 non-null   float64
 8   writing_score                9976 non-null   float64
 9   science_score                9977 non-null   float64
 10  total_score                  9981 non-null   float64
 11  grade                        9997 non-null   object
dtypes: float64(6), object(6)
memory usage: 937.6+ KB

In [51]:
data.describe()

,lunch,test_preparation_course,reading_score,writing_score,science_score,total_score
count,9976.000000,9977.000000,9975.000000,9976.000000,9977.000000,9981.000000
mean,0.644246,0.388694,70.125915,71.415798,66.063045,264.740908
std,0.478765,0.487478,19.026245,18.245360,19.324331,42.304858
min,0.000000,0.000000,17.000000,10.000000,9.000000,89.000000
25%,0.000000,0.000000,57.000000,59.000000,53.000000,237.000000
50%,1.000000,0.000000,71.000000,72.500000,67.000000,268.000000
75%,1.000000,1.000000,85.000000,85.000000,81.000000,294.000000
max,1.000000,1.000000,100.000000,100.000000,100.000000,383.000000

In [52]:
data.isnull().sum()

roll_no                         1
gender                         18
race_ethnicity                 23
parental_level_of_education    22
lunch                          24
test_preparation_course        23
math_score                     24
reading_score                  25
writing_score                  24
science_score                  23
total_score                    19
grade                           3
dtype: int64

In [55]:
data.dropna(inplace=True)

In [56]:
data.isnull().sum()

roll_no                        0
gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
science_score                  0
total_score                    0
grade                          0
dtype: int64